#!/bin/sh
# ./.git/hooks/pre-commit

set -e

cleanup_stash() {
    stash_id=$(git stash list --grep="Pre-commit unstaged changes" --format="%gd")
    if [ -n "$stash_id" ]; then
        git stash pop $stash_id --quiet
    fi
}

git stash push --staged -m "Pre-commit staged changes" --quiet
git stash push --include-untracked -m "Pre-commit unstaged changes" --quiet

stash_id=$(git stash list --grep="Pre-commit staged changes" --format="%gd")
git stash pop $stash_id --index --quiet


trap cleanup_stash EXIT

~/.git-hooks/pre-commit-format-javascript
~/.git-hooks/pre-commit-format-ruby
~/.git-hooks/pre-commit-annotate-models
~/.git-hooks/pre-commit-rspec
