#!/bin/sh
# Dependency: the prettier npm package
set -e

jsfiles=$(git diff --cached --name-only --diff-filter=ACM "*.js" "*.jsx" | tr '\n' ' ')
[ -z "$jsfiles" ] && exit 0

# Prettify all staged .js files
echo "💅 Automatically formatting staged Javascript files using prettier ($(echo $jsfiles | wc -w | awk '{print $1}') total)"
echo "$jsfiles" | xargs prettier --write --loglevel=error

# Add back the modified/prettified files to staging
echo "$jsfiles" | xargs git add

exit 0
